=== SoffidIAM/tools/jascut/src/config/JaSCUTConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="jascut" targetNamespace="jascut">

    <!--
        XML schema for JaSCUT config file.
    -->
    <xs:element name="refactorings" type="refactorings"/>
    <xs:complexType name="refactorings">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="add-override"/>
                <xs:element ref="change-method-signature"/>
                <xs:element ref="factory-method"/>
                <xs:element ref="field-to-method"/>
                <xs:element ref="rename-field"/>
                <xs:element ref="rename-method"/>
                <xs:element ref="rename-type"/>
                <xs:element ref="move-field"/>
                <xs:element ref="move-method"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="add-override" type="add-override"/>
    <xs:complexType name="add-override">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="change-method-signature" type="change-method-signature"/>
    <xs:complexType name="change-method-signature">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="method-orig"/>
            <xs:element ref="args-orig"/>
            <xs:element ref="mods-new" minOccurs="0"/>
            <xs:element ref="return-new" minOccurs="0"/>
            <xs:element ref="method-new" minOccurs="0"/>
            <xs:element ref="args-new" minOccurs="0"/>
            <xs:element ref="throws-new" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="factory-method" type="factory-method"/>
    <xs:complexType name="factory-method">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type-orig"/>
            <xs:element ref="args-orig"/>
            <xs:element ref="type-new"/>
            <xs:element ref="type-args-new" minOccurs="0"/>
            <xs:element ref="method-new"/>
            <xs:element ref="args-new" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="field-to-method" type="field-to-method"/>
    <xs:complexType name="field-to-method">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="field-orig"/>
            <xs:element ref="getter-new"/>
            <xs:element ref="setter-new" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rename-field" type="rename-field"/>
    <xs:complexType name="rename-field">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="field-orig"/>
            <xs:element ref="field-new"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rename-method" type="rename-method"/>
    <xs:complexType name="rename-method">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type"/>
            <xs:element ref="method-orig"/>
            <xs:element ref="args-orig"/>
            <xs:element ref="method-new"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rename-type" type="rename-type"/>
    <xs:complexType name="rename-type">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type-orig"/>
            <xs:element ref="type-new"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="move-field" type="move-field"/>
    <xs:complexType name="move-field">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type-orig"/>
            <xs:element ref="field-orig"/>
            <xs:element ref="type-new"/>
            <xs:element ref="field-new"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="move-method" type="move-method"/>
    <xs:complexType name="move-method">
        <xs:sequence >
            <xs:element ref="description" minOccurs="0"/>
            <xs:element ref="type-orig"/>
            <xs:element ref="method-orig"/>
            <xs:element ref="args-orig"/>
            <xs:element ref="type-new"/>
            <xs:element ref="method-new"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="description" type="xs:string"/>

    <xs:element name="field-orig" type="xs:string"/>

    <xs:element name="field-new" type="xs:string"/>

    <xs:element name="method-orig" type="xs:string"/>

    <xs:element name="method-new" type="xs:string"/>

    <xs:element name="args-orig" type="xs:string"/>

    <xs:element name="args-new" type="args-new"/>
    <xs:complexType name="args-new">
        <xs:sequence>
            <xs:element ref="arg" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="arg" type="arg"/>
    <xs:complexType name="arg">
        <xs:sequence minOccurs="0">
            <xs:element ref="type"/>
            <xs:element ref="name"/>
            <xs:element ref="value"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:integer"/>
    </xs:complexType>

    <xs:element name="name" type="xs:string"/>

    <xs:element name="value" type="value"/>
    <xs:complexType name="value">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="kind" type="xs:string"/>
                <xs:attribute name="ref" type="xs:integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="type" type="xs:string"/>

    <xs:element name="type-orig" type="xs:string"/>

    <xs:element name="type-args-new" type="xs:string"/>

    <xs:element name="type-new" type="xs:string"/>

    <xs:element name="mods-new" type="xs:string"/>

    <xs:element name="return-new" type="xs:string"/>

    <xs:element name="throws-new" type="xs:string"/>

    <xs:element name="getter-new" type="xs:string"/>

    <xs:element name="setter-new" type="xs:string"/>

</xs:schema>

=== SoffidIAM/tools/jascut/src/config/jascut-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<refactorings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="jascut JaSCUTConfig.xsd"
    xmlns="jascut">

    <description>Test</description>

    <change-method-signature>
        <type>lib.GenericPrinter</type>
        <method-orig>print</method-orig>
        <args-orig>T extends java.lang.Object</args-orig>
        <method-new>printX</method-new>
        <args-new>
            <arg>
                <type>java.lang.String</type>
                <name>t</name>
                <value kind="reference">0</value>
            </arg>
            <arg>
                <type>int</type>
                <name>n</name>
                <value kind="literal">42</value>
            </arg>
        </args-new>
    </change-method-signature>

    <rename-method>
        <type>lib.Printer</type>
        <method-orig>print</method-orig>
        <args-orig/>
        <method-new>printMessage</method-new>
    </rename-method>

    <rename-field>
        <description>Rename height to width</description>
        <type>java.awt.Dimension</type>
        <field-orig>height</field-orig>
        <field-new>width</field-new>
    </rename-field>

</refactorings>

=== SoffidIAM/tools/jascut/src/config/sax1-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<refactorings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="jascut JaSCUTConfig.xsd"
    xmlns="jascut">

    <description>Upgrade to SAX 2</description>

    <rename-type>
        <type-orig>org.xml.sax.helpers.AttributeListImpl</type-orig>
        <type-new>org.xml.sax.helpers.AttributesImpl</type-new>
    </rename-type>

    <rename-type>
        <type-orig>org.xml.sax.HandlerBase</type-orig>
        <type-new>org.xml.sax.helpers.DefaultHandler</type-new>
    </rename-type>

    <rename-type>
        <type-orig>org.xml.sax.helpers.ParserFactory</type-orig>
        <type-new>org.xml.sax.helpers.XMLReaderFactory</type-new>
    </rename-type>

    <rename-type>
        <type-orig>org.xml.sax.AttributeList</type-orig>
        <type-new>org.xml.sax.Attributes</type-new>
    </rename-type>

    <rename-type>
        <type-orig>org.xml.sax.DocumentHandler</type-orig>
        <type-new>org.xml.sax.ContentHandler</type-new>
    </rename-type>

    <rename-type>
        <type-orig>org.xml.sax.Parser</type-orig>
        <type-new>org.xml.sax.XMLReader</type-new>
    </rename-type>

    <rename-method>
        <type>org.xml.sax.AttributeList</type>
        <method-orig>getName</method-orig>
        <args-orig>int</args-orig>
        <method-new>getQName</method-new>
    </rename-method>

    <rename-method>
        <type>org.xml.sax.Parser</type>
        <method-orig>setDocumentHandler</method-orig>
        <args-orig>org.xml.sax.DocumentHandler</args-orig>
        <method-new>setContentHandler</method-new>
    </rename-method>

    <rename-method>
        <type>org.xml.sax.helpers.AttributeListImpl</type>
        <method-orig>setAttributeList</method-orig>
        <args-orig>org.xml.sax.AttributeList</args-orig>
        <method-new>setAttributes</method-new>
    </rename-method>

    <rename-method>
        <type>org.xml.sax.helpers.ParserFactory</type>
        <method-orig>makeParser</method-orig>
        <args-orig/>
        <method-new>createXMLReader</method-new>
    </rename-method>

    <rename-method>
        <type>org.xml.sax.helpers.ParserFactory</type>
        <method-orig>makeParser</method-orig>
        <args-orig>java.lang.String</args-orig>
        <method-new>createXMLReader</method-new>
    </rename-method>

    <change-method-signature>
        <type>org.xml.sax.helpers.AttributeListImpl</type>
        <method-orig>addAttribute</method-orig>
        <args-orig>java.lang.String, java.lang.String, java.lang.String</args-orig>
        <args-new>
            <arg>
                <type>java.lang.String</type>
                <name>uri</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>localName</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>qName</name>
                <value kind="reference">0</value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>type</name>
                <value kind="reference">1</value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>value</name>
                <value kind="reference">2</value>
            </arg>
        </args-new>
    </change-method-signature>

    <change-method-signature>
        <type>org.xml.sax.DocumentHandler</type>
        <method-orig>startElement</method-orig>
        <args-orig>java.lang.String, org.xml.sax.AttributeList</args-orig>
        <args-new>
            <arg>
                <type>java.lang.String</type>
                <name>namespaceURI</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>localName</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>qName</name>
                <value kind="reference">0</value>
            </arg>
            <arg>
                <type>org.xml.sax.Attributes</type>
                <name>atts</name>
                <value kind="reference">1</value>
            </arg>
        </args-new>
    </change-method-signature>

    <change-method-signature>
        <type>org.xml.sax.DocumentHandler</type>
        <method-orig>endElement</method-orig>
        <args-orig>java.lang.String</args-orig>
        <args-new>
            <arg>
                <type>java.lang.String</type>
                <name>namespaceURI</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>localName</name>
                <value kind="literal"></value>
            </arg>
            <arg>
                <type>java.lang.String</type>
                <name>qName</name>
                <value kind="reference">0</value>
            </arg>
        </args-new>
    </change-method-signature>

    <change-method-signature>
        <type>org.xml.sax.HandlerBase</type>
        <method-orig>notationDecl</method-orig>
        <args-orig>java.lang.String, java.lang.String, java.lang.String</args-orig>
        <throws-new>org.xml.sax.SAXException</throws-new>
    </change-method-signature>

    <change-method-signature>
        <type>org.xml.sax.HandlerBase</type>
        <method-orig>resolveEntity</method-orig>
        <args-orig>java.lang.String, java.lang.String</args-orig>
        <throws-new>org.xml.sax.SAXException, java.io.IOException</throws-new>
    </change-method-signature>

    <change-method-signature>
        <type>org.xml.sax.HandlerBase</type>
        <method-orig>unparsedEntityDecl</method-orig>
        <args-orig>java.lang.String, java.lang.String, java.lang.String, java.lang.String</args-orig>
        <throws-new>org.xml.sax.SAXException</throws-new>
    </change-method-signature>

</refactorings>

=== SoffidIAM/tools/jascut/src/config/Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<refactorings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="jascut JaSCUTConfig.xsd"
    xmlns="jascut">

    <description>Test</description>

    <rename-type>
        <type-orig>lib.Car</type-orig>
        <type-new>lib.Bus</type-new>
    </rename-type>
    
    <rename-method>
        <type>lib.Car</type>
        <method-orig>start</method-orig>
        <args-orig/>
        <method-new>startEngine</method-new>
    </rename-method>

</refactorings>

=== SoffidIAM/tools/jascut/src/config/jascut-config_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<refactorings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="jascut JaSCUTConfig.xsd"
    xmlns="jascut">

    <change-method-signature>
        <type>java.lang.Object</type>
        <method-orig>clone</method-orig>
        <args-orig></args-orig>
        <mods-new>static</mods-new>
        <return-new>java.lang.Exception</return-new>
        <method-new>CLONE</method-new>
        <args-new></args-new>
        <throws-new>java.lang.Exception</throws-new>
    </change-method-signature>

    <rename-method>
        <description>printf to printf2</description>
        <type>java.io.PrintStream</type>
        <method-orig>printf</method-orig>
        <args-orig>java.lang.String, java.lang.Object...</args-orig>
        <method-new>printf2</method-new>
    </rename-method>
    <!--
    <rename-field>
        <type>java.awt.Dimension</type>
        <field-orig>height</field-orig>
        <field-new>width</field-new>
    </rename-field>
    <rename-field>
        <type>java.awt.Dimension</type>
        <field-orig>width</field-orig>
        <field-new>height</field-new>
    </rename-field>
    -->
    <!--
    <convert-to-diamond/>
    <format-literal groups="3" minimum-length="8"/>
    -->
    <!--
    <rename-method>
        <description>Rename...</description>
        <type>lib.Service</type>
        <method-orig>print</method-orig>
        <args-orig>T extends java.lang.Object</args-orig>
        <method-new>printA</method-new>
    </rename-method>
    -->
    <!--
    <rename-method>
        <description>Rename...</description>
        <type>lib.Service</type>
        <method-orig>print</method-orig>
        <args-orig>K extends java.lang.Object,V extends java.lang.Object</args-orig>
        <method-new>printB</method-new>
    </rename-method>
    <rename-method>
        <description>Rename Service.read() to Service.readInt()</description>
        <type>lib.Service</type>
        <method-orig>read</method-orig>
        <args-orig></args-orig>
        <method-new>readInt</method-new>
        <args-new></args-new>
    </rename-method>
    <rename-method>
        <type>lib.Service</type>
        <method-orig>print</method-orig>
        <args-orig>int</args-orig>
        <method-new>printInt</method-new>
        <args-new>
            <arg ref="0"/>
        </args-new>
    </rename-method>
    -->
    
</refactorings>
